### PR TITLE
Upgrade bitshuffle to v0.3.1

### PR DESCRIPTION
**Pull request by maropu**
This pr is along with https://github.com/kiyo-masui/bitshuffle/pull/58

### CODE REVIEW

**Comment by xerial** [comment]
OK. I'll build native libraries with bitshuffle 0.3.1

**Comment by xerial** [comment]
@maropu building native libraries for 64-bit cpu types fails. Could you check what is wrong?
```
$ make linux64                                                                   [10:45:26 Feb 06 2017]
docker run --rm -ti -v $PWD:/work xerial/centos5-linux-x86_64-pic bash -c 'make clean-native native OS_NAME=Linux OS_ARCH=x86_64'
Makefile.common:6: Set JAVA_HOME environment variable
/bin/sh: /bin/java: No such file or directory
/bin/sh: /bin/java: No such file or directory
/bin/sh: /bin/java: No such file or directory
find: invalid predicate `'
rm -rf target/snappy-1.1.4-Linux-x86_64
g++ -Ilib/inc_linux -I/include -O2 -fPIC -fvisibility=hidden -m64 -Ilib/include -Itarget/snappy-1.1.4 -Itarget/bitshuffle-0.3.1/src -c target/snappy-1.1.4/snappy-sinksource.cc -o target/snappy-1.1.4-Linux-x86_64/snappy-sinksource.o
g++ -Ilib/inc_linux -I/include -O2 -fPIC -fvisibility=hidden -m64 -Ilib/include -Itarget/snappy-1.1.4 -Itarget/bitshuffle-0.3.1/src -c target/snappy-1.1.4/snappy-stubs-internal.cc -o target/snappy-1.1.4-Linux-x86_64/snappy-stubs-internal.o
g++ -Ilib/inc_linux -I/include -O2 -fPIC -fvisibility=hidden -m64 -Ilib/include -Itarget/snappy-1.1.4 -Itarget/bitshuffle-0.3.1/src -c target/snappy-1.1.4/snappy.cc -o target/snappy-1.1.4-Linux-x86_64/snappy.o
g++ -Ilib/inc_linux -I/include -O2 -fPIC -fvisibility=hidden -m64 -Ilib/include -Itarget/snappy-1.1.4 -Itarget/bitshuffle-0.3.1/src -U__AVX2__ -msse2 -c target/bitshuffle-0.3.1/src/bitshuffle_core.c -o target/snappy-1.1.4-Linux-x86_64/bitshuffle_core.o
In file included from /usr/include/stdlib.h:438:0,
                 from target/bitshuffle-0.3.1/src/bitshuffle_core.h:42,
                 from target/bitshuffle-0.3.1/src/bitshuffle_core.c:12:
/usr/include/sys/types.h:198:1: error: conflicting declaration 'typedef long int int64_t'
 __intN_t (64, __DI__);
 ^
In file included from target/bitshuffle-0.3.1/src/bitshuffle_core.c:12:0:
target/bitshuffle-0.3.1/src/bitshuffle_core.h:39:31: error: 'int64_t' has a previous declaration as 'typedef long long int int64_t'
   typedef long long           int64_t;
                               ^
make: *** [target/snappy-1.1.4-Linux-x86_64/bitshuffle_core.o] Error 1
make: *** [linux64] Error 2
```

**Comment by maropu** [comment]
okay, I'll check.

**Comment by maropu** [comment]
okay, I checked this worked well in `linux64`.

**Comment by xerial** [comment]
Thanks! Merged in #164

**Pull request merged**
