### PR TITLE
Feature: Windows aarch64 (arm64), armv7 support

### PR DESCRIPTION
**Pull request by xerial**
Native lib build is failing because of some issues in cmake 3.24.x. 
https://gitlab.kitware.com/cmake/cmake/-/issues/24180

```
-- Check size of unsigned short
CMake Error at /usr/share/cmake-3.24/Modules/CheckTypeSize.cmake:146 (try_compile):
  Cannot copy output executable

    ''

  to destination specified by COPY_FILE:

    '/work/target/snappy-1.1.10-Windows-aarch64/CMakeFiles/CheckTypeSize/CMAKE_SIZEOF_UNSIGNED_SHORT.bin'

  Unable to find the executable at any of:

    /work/target/snappy-1.1.10-Windows-aarch64/CMakeFiles/CMakeTmp/cmTC_accdd
    /work/target/snappy-1.1.10-Windows-aarch64/CMakeFiles/CMakeTmp/Debug/cmTC_accdd
    /work/target/snappy-1.1.10-Windows-aarch64/CMakeFiles/CMakeTmp/Development/cmTC_accdd

Call Stack (most recent call first):
  /usr/share/cmake-3.24/Modules/CheckTypeSize.cmake:277 (__check_type_size_impl)
  /usr/share/cmake-3.24/Modules/TestBigEndian.cmake:55 (CHECK_TYPE_SIZE)
  /usr/share/cmake-3.24/Modules/TestBigEndian.cmake:37 (__TEST_BIG_ENDIAN_LEGACY_IMPL)
  CMakeLists.txt:55 (test_big_endian)
```

Using cmake 3.26.4 still didn't solve this issue:
```
-- Check size of unsigned short
CMake Error at /opt/cmake-3.26.4-linux-x86_64/share/cmake-3.26/Modules/CheckTypeSize.cmake:148 (try_compile):
  Cannot copy output executable

    ''

  to destination specified by COPY_FILE:

    '/work/target/snappy-1.1.10-Windows-aarch64/CMakeFiles/CheckTypeSize/CMAKE_SIZEOF_UNSIGNED_SHORT.bin'

  because:

    No such file or directory (input)
```

### CODE REVIEW

**Comment by imsudiproy** [comment]
I'll have a look, if I can get a solution

**Comment by xerial** [comment]
Probably we should merge the PR without adding windows-arm64 and armv7 targets to the native-all

**Comment by imsudiproy** [comment]
Hi @xerial , I am raising PR for Windows arm64 support.

**Comment by xerial** [comment]
Closing in favor of #511

**Pull request closed without merging**
