### PR TITLE
Adding s390x support in Travis

### PR DESCRIPTION
**Pull request by namrata-ibm**
As Travis CI [officially supports](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z) s390x builds, adding support for same.

### CODE REVIEW

**Comment by xerial** [comment]
@namrata-ibm Thanks for the update. Now, I'm inclining to migrate to GitHub Actions because of its convenience in future. I'm not sure it supports s390x arch, though.

**Comment by namrata-ibm** [comment]
@xerial , there seems to be a third-party [GitHub Action](https://github.com/marketplace/actions/run-on-architecture), although Travis runs native builds for s390x.

**Comment by namrata-ibm** [comment]
@xerial could you please update on this?

**Comment by namrata-ibm** [comment]
@xerial when lang scala is selected, java does not come preinstalled for s390x, I have added steps for java installation to resolve the build failure. Please let me know your comments.

**Comment by namrata-ibm** [comment]
@xerial , could you please have a look?

**Comment by namrata-ibm** [comment]
@xerial any updates on this?

**Comment by xerial** [comment]
Let me merge this and I'll use Travis for s390x build and GitHub Actions for the others.

**Pull request merged**
