### PR TITLE
update libsnappyjava.so for ppc64le to make it compat with rhel 7

### PR DESCRIPTION
**Pull request by josiahsams**
This PR will address the issue reported in https://github.com/xerial/snappy-java/issues/220 for ppc64le arch.

The GLIBC 2.22 dependency is only due to the following ,
```
$ objdump -T ./libsnappyjava.so | grep GLIBC_2.22
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.22  __tls_get_addr_opt
```
To circumvent this call, we can use linker flags `--no-tls-optimize,--no-tls-get-addr-optimize` to disable it.

The .so file attached to this PR is compiled with these flags and relevant changes are made with Makefile and its applicable only for ppcle64 arch.

Ref: https://stackoverflow.com/questions/58958084/disabling-tls-get-addr-opt-for-ppc

### CODE REVIEW

**Comment by xerial** [comment]
@josiahsams Can we add this configuration to Makefile.common instead? 
https://github.com/xerial/snappy-java/blob/acaca7f9b12c03bfc146553e4cfaadb60679f916/Makefile.common#L111-L120

**Comment by josiahsams** [comment]
@xerial , Moved the linker flags to Makefile.common. 
Thanks.

**Comment by xerial** [comment]
Thanks. I'll just release 1.1.7.4 as 1.1.7.x are minor fixes over 1.1.7

**Comment by jamesbroadhead** [comment]
Hi @xerial -

Do you have an intended release date for 1.1.7.4? 
We'd like to upgrade to regain ppc64le support. 
(apologies if I missed this somewhere) 

Thank you -- James

**Comment by d0lphis** [comment]
Hi @xerial,

There's a ticket from our side to waiting for this fix, any update for the release date of 1.1.7.4?

Thanks

**Comment by HeartSaVioR** [comment]
Hello @xerial 

we hit the issue on ppc64le + RHEL 7 and would like to upgrade to 1.1.7.4. Any update for the new release?

**Comment by xerial** [comment]
@HeartSaVioR Just released snappy-java 1.1.7.4 with this fix. Please try it.

**Pull request merged**
