### PR TITLE
Support Linux on IBM z Systems

### PR DESCRIPTION
**Pull request by bryanpkc**
Snappy-Java has been patched to allow it to be built and used on Linux on IBM z Systems ("s390x"). We would like to contribute the code upstream.

### CODE REVIEW

**Comment by xerial** [comment]
Looks good. You may need to add configuration lines for OSGi:
https://github.com/xerial/snappy-java/blob/develop/build.sbt#L116

**Comment by bryanpkc** [comment]
Thanks for the tip; I have added the OSGi configuration line for Linux-s390x.

**Comment by xerial** [comment]
And also could you add the native library of s390x at src/main/resources/.../ libsnappyjava.so ?

Thanks

**Comment by bryanpkc** [comment]
Done.

**Comment by xerial** [comment]
Thanks!

**Pull request merged**
