### PR TITLE
Cross building snappy-java using docker

### PR DESCRIPTION
**Pull request by xerial**
Based on #137, this PR will add support for cross compiler based native library build:
- [x] Windows
- [x] Linux x86, x64
  - [x] Build docker image for g++ built with -fPIC option
- [x] Linux arm (armv5, v6, v7 and android-arm)
  - [x] Fix OSInfo to support various arm arch types
- [x] Mac OS X
- [x] PowerPC
- [x] aarch64
- [x] Build native libraries on Travis CI + docker 
- [x] Upload the latest snapshot to Sonatype in Travis CI
- [x] Fix build.sbt (for OSGi)
- (TODO) Ask contributions of native libraries for platforms where no cross compiler image of docker is available  (e.g., FreeBSD, IBM s390, AIX, etc.)

### CODE REVIEW

**Comment by xerial** [comment]
Now `make native-all` can be used.

**Comment by odaira** [comment]
Do you need any help in building native libraries on s390 and AIX? :-)

**Comment by xerial** [comment]
@odaira Nice to see you @odaira san :) And yes. Please run `make native` on s390 and AIX and send the results as PR.

**Comment by odaira** [comment]
OK, I have just started working on it, but it seems to take some time as I have to start with environment set-up.  Stay tuned....

**Comment by odaira** [comment]
I think the native libraries for Linux/s390x and AIX/ppc* are up-to-date for 1.1.3, but do you still want me to build them?

**Comment by xerial** [comment]
@odaira Yes because snappy-java-1.1.3-M1 newly adds BitShuffle API, which needs recompilation. Let's move this discussion to another ticket.

**Comment by xerial** [comment]
@odaira Created #156

**Pull request merged**
