### PR TITLE
#302 Fixed running snappy-java as OSGi bundle on Apple Silicon (M1 Pro)

### PR DESCRIPTION
**Pull request by zh-muxa**
Fixing issue https://github.com/xerial/snappy-java/issues/302

### CODE REVIEW

**Comment by chrisrueger** [comment]
We have this issue too and the fix seems to address this. 
Our error with 1.1.8.4 is:

```
Unresolved requirement: Require-Capability: osgi.native; native.paths.8:List<String>="org/xerial/snappy/native/Linux/x86_64/libsnappyjava.so"; native.paths.17:List<String>="org/xerial/snappy/native/SunOS/x86/libsnappyjava.so"; native.paths.7:List<String>="org/xerial/snappy/native/Linux/x86_64/libsnappyjava.so"; native.paths.16:List<String>="org/xerial/snappy/native/AIX/ppc64/libsnappyjava.a"; native.paths.19:List<String>="org/xerial/snappy/native/SunOS/sparc/libsnappyjava.so"; native.paths.9:List<String>="org/xerial/snappy/native/Linux/x86/libsnappyjava.so"; native.paths.18:List<String>="org/xerial/snappy/native/SunOS/x86_64/libsnappyjava.so"; native.paths.13:List<String>="org/xerial/snappy/native/Linux/ppc64/libsnappyjava.so"; native.paths.12:List<String>="org/xerial/snappy/native/Linux/armv7/libsnappyjava.so"; native.paths.15:List<String>="org/xerial/snappy/native/AIX/ppc/libsnappyjava.a"; native.paths.14:List<String>="org/xerial/snappy/native/Linux/s390x/libsnappyjava.so"; native.paths.11:List<String>="org/xerial/snappy/native/Linux/arm/libsnappyjava.so"; native.paths.10:List<String>="org/xerial/snappy/native/Linux/aarch64/libsnappyjava.so"; native.paths.0:List<String>="org/xerial/snappy/native/Windows/x86_64/snappyjava.dll"; native.paths.2:List<String>="org/xerial/snappy/native/Windows/x86_64/snappyjava.dll"; native.paths.1:List<String>="org/xerial/snappy/native/Windows/x86_64/snappyjava.dll"; native.paths.4:List<String>="org/xerial/snappy/native/Mac/x86/libsnappyjava.dylib"; native.paths.3:List<String>="org/xerial/snappy/native/Windows/x86/snappyjava.dll"; native.paths.6:List<String>="org/xerial/snappy/native/Linux/x86_64/libsnappyjava.so"; native.paths.5:List<String>="org/xerial/snappy/native/Mac/x86_64/libsnappyjava.dylib"; filter:="(|(&(osgi.native.osname~=win32)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=win32)(osgi.native.processor~=x64))(&(osgi.native.osname~=win32)(osgi.native.processor~=amd64))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86))(&(osgi.native.osname~=macosx)(osgi.native.processor~=x86))(&(osgi.native.osname~=macosx)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=linux)(osgi.native.processor~=x64))(&(osgi.native.osname~=linux)(osgi.native.processor~=amd64))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86))(&(osgi.native.osname~=linux)(osgi.native.processor~=aarch64))(&(osgi.native.osname~=linux)(osgi.native.processor~=arm))(&(osgi.native.osname~=linux)(osgi.native.processor~=arm_le))(&(osgi.native.osname~=linux)(osgi.native.processor~=ppc64le))(&(osgi.native.osname~=linux)(osgi.native.processor~=s390x))(&(osgi.native.osname~=aix)(osgi.native.processor~=ppc))(&(osgi.native.osname~=aix)(osgi.native.processor~=ppc64))(&(osgi.native.osname~=sunos)(osgi.native.processor~=x86))(&(osgi.native.osname~=sunos)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=sunos)(osgi.native.processor~=sparc)))"
```

**Comment by xerial** [comment]
Merged. Thanks!

**Comment by chrisrueger** [comment]
@xerial  Thanks. Is there any estimate for a new release including this fix? Currently on maven central [1.1.8.4](https://mvnrepository.com/artifact/org.xerial.snappy/snappy-java/1.1.8.4) is the most recent from Jan 2021

**Comment by giftkugel** [comment]
> @xerial Thanks. Is there any estimate for a new release including this fix? Currently on maven central [1.1.8.4](https://mvnrepository.com/artifact/org.xerial.snappy/snappy-java/1.1.8.4) is the most recent from Jan 2021

Would also like to know when to expect this fix as part of a release.

**Pull request merged**
