### PR TITLE
Fix `Could not initialize class org.xerial.snappy.Snappy` bug for MacOS

### PR DESCRIPTION
**Pull request by asdf2014**

### CODE REVIEW

**Comment by asdf2014** [comment]
@xerial PTAL

**Comment by xerial** [comment]
@asdf2014 It seems this issue is Mac OS X version specific issue. I'm using Mojave, and snappy-java works fine. What version of Mac OS X are you using?

**Comment by xerial** [comment]
And also note that we've already dropped a support for Mac OS X 32-bit (x86), but it should work. So changing the library file name is not ideal for Mac/x86

**Comment by asdf2014** [comment]
Hi, @xerial . Thanks for your reply. I think this is a common problem on MacOS. I am using MacOS x86_64 and encountered this error.

```bash
$ uname -a
Darwin yuzhouwan.com.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

**Comment by xerial** [comment]
@asdf2014 Thanks for the update. Now I don't have an environment to use the latest Mac OS X, I need to confirm the true cause of this error. 

It seems you have added src/main/resources/org/xerial/snappy/native/Mac/x86_64/libsnappyjava.dylib file, but if we just rename the existing .jnilib file to .dylib, what will happen? I'd like to see the stack trace where the error occurs. If the error is still shown, it looks like the native library incompatibility problem between Mac OS  X versions.

**Comment by asdf2014** [comment]
@xerial In my environment, if I just rename `libsnappyjava.jnilib` to `libsnappyjava.dylib`, the problem can still be solved without reporting any errors. :smile:

**Comment by xerial** [comment]
@asdf2014 Ok. Then, could you fix the PR so that it will just rename libsnappyjava.jnilib to .dylib? After that, I'll merge it and release snappy-java-1.1.8.1

**Comment by asdf2014** [comment]
@xerial The useless `libsnappyjava.jnilib` file has been deleted. PTAL.

**Comment by xerial** [comment]
LGTM. Thanks for the fix!

**Comment by asdf2014** [comment]
@xerial You are welcome :smile:

**Pull request merged**
