### PR TITLE
Pool byte[] and direct ByteBuffer

### PR DESCRIPTION
**Pull request by bokken**
Pool byte[] and direct ByteBuffer instances for reuse by Framed
implementation.

https://github.com/xerial/snappy-java/issues/233

### CODE REVIEW

**Comment by bokken** [comment]
@xerial, any idea when this could get reviewed, merged and released?

**Comment by xerial** [comment]
@bokken oops. Sorry. Checking this PR has been slipped from my list.

**Comment by bokken** [comment]
@xerial no problem. Looking forward to having this available.

**Comment by bokken** [comment]
@xerial just bumping this issue. Thanks.

**Comment by xerial** [comment]
ok. Overall it looks good to me.

**Comment by bokken** [comment]
@xerial, thanks for merging. When are you planning on releasing?

**Comment by xerial** [comment]
I'm now releasing 1.1.7.4 with this change.

**Pull request merged**
